package com.stumosys.controler;

import java.util.List;

import com.stumosys.domain.*;
import com.stumosys.exception.StumosysException;
import com.stumosys.shared.BookSalesRecord;
import com.stumosys.shared.ExamTable;
import com.stumosys.shared.Library;
import com.stumosys.shared.Noticeboard;
import com.stumosys.shared.School;
import com.stumosys.shared.StudentDetail;
import com.stumosys.shared.StudentPerformance;
import com.stumosys.shared.SupProduct;
import com.stumosys.shared.TimeTable;
import com.stumosys.shared.UserProduct;

public interface SmsController {
	
	/* Return type int method */
	public int getStudentId(String stuRollNo);
	public int getTotalParent(String personID);
	public int getTotalTeacher(String personID);
	/* Return type String method */
	public String getRoll(String personID);
	public String getRollNumber(String personID);
	public String forgot(LoginAccess loginaccess);
	public String getStudClsSection(String rollnumber);
	public String totalStudent(LoginAccess loginaccess);
	public String otpvarify(String otp, String username);
	public String userLogin(LoginAccess loginaccess) throws StumosysException;
	public String getZipList(StudentDataBean studentdatabean);
	public String getZipList1(StudentDataBean studentdatabean);
	public String getStudentClass(String stuRollNo, String personID);
	public String setNewpassword(String newPassword, String username);
	public String updateStaff(String personID, StaffDataBean staffDataBean);
	public String deleteStaff(String personID, StaffDataBean staffDataBean);
	public String deleteBook(String personID, LibraryDataBean libraryDataBean);
	public String updateParent(String personID, ParentsDataBean parentsDataBean);
	public String deleteParent(String personID, ParentsDataBean parentsDataBean);
	public String insertTeacher(String personID, TeacherDataBean teacherDataBean);
	public String insertStudent(String personID, StudentDataBean studentDataBean);
	public String updateTeacher(String personID, TeacherDataBean teacherDataBean);
	public String deleteTeacher(String personID, TeacherDataBean teacherDataBean);
	public String insertParents(String personID, ParentsDataBean parentsDataBean);	
	public String examCheck(TimeTableDataBean timeTableDataBean, String personID);
	public String updateLibrary(String personID, LibraryDataBean libraryDataBean);
	public String insertLibrary(String personID, LibraryDataBean libraryDataBean);
	public String getStudentEdit(StudentDataBean studentDataBean, String personID);
	public String checkTeacherID(TeacherDataBean teacherDataBean, String personID);
	public String examRecords(TimeTableDataBean timeTableDataBean, String personID);
	public String getStudentDelete(String personID, StudentDataBean studentDataBean);
	public String checkValidateZip(String personID, TeacherDataBean teacherDataBean);
	public String timeTableView(TimeTableDataBean timeTableDataBean, String personID);
	public String getexamupdate(String personID, TimeTableDataBean timeTableDataBean);
	public String studentList(String personID, AttendanceDataBean attendanceDataBean);
	public String classPeriod(AttendanceDataBean attendanceDataBean, String personID);
	public String subjectValues(TimeTableDataBean timeTableDataBean, String personID);
	public String insertBookBorrowed(String personID, LibraryDataBean libraryDataBean);
	public String classStudent(AttendanceDataBean attendanceDataBean, String personID);
	public String leaveRequest(AttendanceDataBean attendanceDataBean, String personID);
	public String addReportCard(String personID, ReportCardDataBean reportCardDataBean);
	public String checkStudentRollno(StudentDataBean studentDataBean, String stuRollNo);
	public String getexamEditList(String personID, TimeTableDataBean timeTableDataBean);
	public String updateNotice(String personID, NoticeBoardDataBean noticeBoardDataBean);
	public String attendanceView(String personID, AttendanceDataBean attendanceDataBean);
	public String studentAttView(String personID, AttendanceDataBean attendanceDataBean);
	public String deleteNotice(String personID, NoticeBoardDataBean noticeBoardDataBean);
	public String changeSubjectCode(String personID, TimeTableDataBean timeTableDataBean);
	public String getexamRecordsList(String personID,TimeTableDataBean timeTableDataBean);
	public String attendanceStatus(String personID, AttendanceDataBean attendanceDataBean);	
	public String leaveRequsetView(AttendanceDataBean attendanceDataBean, String personID);
	public String updateAttendance(AttendanceDataBean attendanceDataBean, String personID);
	public String insertNoticeBoard(String personID, NoticeBoardDataBean noticeBoardDataBean);		
	public String leaveRequsetApproval(AttendanceDataBean attendanceDataBean, String personID);
	public String attendanceChartStudent(String personID, AttendanceDataBean attendanceDataBean);
	public String teacherTimeTable(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String classTimeTableView(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String attendanceChartStudentYear(String personID, AttendanceDataBean attendanceDataBean);
	public String saveClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String getLibrarianInfo(String personID, String libID, LibrarianDataBean librarianDataBean);
	public String updateClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String deleteClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID); 
	public String getPerClass(StudentPerformanceDataBean studentPerformanceDataBean, String personID);
	public String getPerformEdit(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public String getperformDelete(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public String insertStudentPerform(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public String timeTableInsert(String personID,TimeTableDataBean timeTableDataBean, List<TimeTableDataBean> timesBean);
	public String getParentRollNumber(String personID, LoginAccess loginAccess);
	public String addBookOrder(String personID, BookSaleDataBean bookSaleDataBean);
	public String getBookDelete(String personID, BookSaleDataBean bookSaleDataBean);
	public String getBookUpdate(String personID, BookSaleDataBean bookSaleDataBean);
	public String insertAddBook(String personID, BookSaleDataBean bookSaleDataBean);
	public String getmailsID(StudentPerformanceDataBean studentPerformanceDataBean);
	public String checkLibrarianID(LibrarianDataBean librarianDataBean, String libID);
	public String editReportCard(String personID, ReportCardDataBean reportCardDataBean);
	public String attendanceChart(String personID, AttendanceDataBean attendanceDataBean);
	public String getReportBarChart(String personID, ReportCardDataBean reportCardDataBean);
	public String classTimeTable(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String insertLibrarian(String personID, LibrarianDataBean librarianDataBean);
	public String parentstuAttView(String personID, AttendanceDataBean attendanceDataBean);
	public String insertStaff(String personID, StaffDataBean staffDataBean);
	public String staffidcheck(StaffDataBean staffDataBean,String staStaffID);
	public String getStaffRollNumber(String personID, LoginAccess loginaccess);
	public String getAttendanceList(AttendanceDataBean attendanceDataBean);
	public String updateAttendance(AttendanceDataBean attendanceDataBean);
	public String deleteLibrarian(String personID, LibrarianDataBean librarianDataBean);
	public String classChange(HomeworkDatabean homeworkDatabean, String personID);
	public String libUpdate(LibrarianDataBean librarianDataBean, String personID);
	public String checkHomeWork(HomeworkDatabean homeworkDatabean,String personID);
	public String homeWorkInsert(HomeworkDatabean homeworkDatabean,String personID);
	public String updateHomeWork(HomeworkDatabean homeworkDatabean,String personID);
	public String deleteHomeWork(HomeworkDatabean homeworkDatabean,String personID);
	public String classChange(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String checkExtraClass(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String insertExtraClass(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String leaveRequsetReject(AttendanceDataBean attendanceDataBean, String personID);
	public String toReturnBook(String personID, LibraryDataBean libraryDataBean);
	public String timeTableICheck(String personID, TimeTableDataBean timeTableDataBean);
	public String insertclass(String personID, String schoolID,LibrarianDataBean librarianDataBean);
	public String insertsubject(String personID,String schoolID,LibrarianDataBean librarianDataBean);
	public String takeattendance(String personID,AttendanceDataBean attendanceDataBean);
	public String getperstudentList(StudentPerformanceDataBean studentPerformanceDataBean,String personID);
	public String bookstockin(BookSaleDataBean bookSaleDataBean, String personID);
	public String stockinbookQuentity(LibraryDataBean libraryDataBean,String personID);
	public String borrowrinsertbook(String personID,LibraryDataBean libraryDataBean);
	public String getNotReturnedBooks(String personID,LoginAccess loginaccess);
	public String validatecalss(LibrarianDataBean librarianDataBean,String schoolID);
	public String validatesubject(LibrarianDataBean librarianDataBean,String schoolID);	
	public String updatesujectname(String personID, LibrarianDataBean librarianDataBean);
	public String deleteclasssec(String personID, LibrarianDataBean librarianDataBean);	
	public String deletesubname(String personID, LibrarianDataBean librarianDataBean);
	public String getexammarksupdate(String personID, TimeTableDataBean timeTableDataBean);	
	public String getexammarkgrade(ReportCardDataBean reportCardDataBean);
	public String feessave(String personID, PaymentDatabean paymentDatabean);
	public String checkExtraPeriod(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String insertExtraPeriod(String personID, ClassTimeTableDataBean classTimeTableDataBean);	
	public String classTimeTableDelete(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String checkupdateClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String insertStaff2(String personID, StaffDataBean staffDataBean);
	public String getPerClassList1(String personID, PaymentDatabean paymentDatabean);
	public String getPerClass(PaymentDatabean paymentDatabean);
	public String insertfees(String personID, PaymentDatabean paymentDatabean);
	public String classStudentFeesView(String personID, PaymentDatabean paymentDatabean);
	public String feespay(String personID, PaymentDatabean paymentDatabean);
	public String paymentview(String personID, PaymentDatabean paymentDatabean);
	public String updatePayment(String personID, PaymentDatabean paymentDatabean);
	public String deletePayment(String personID, PaymentDatabean paymentDatabean);
	public String approveRejectFees(String personID, PaymentDatabean paymentDatabean);
	public String deletebooksale(String personID, BookSaleDataBean bookSaleDataBean);
	public String bookOrderUpdate(String personID, BookSaleDataBean bookSaleDataBean);
	public String bookpaymentupload(String personID, BookSaleDataBean bookSaleDataBean);
	public String bookpayemtreject(String personID, BookSaleDataBean bookSaleDataBean);
	public String bookpayemtapprove(String personID, BookSaleDataBean bookSaleDataBean);
	public String performanceCheck(StudentPerformanceDataBean studentPerformanceDataBean);
	public String editclasssec(String personID,LibrarianDataBean librarianDataBean);
	public String updateAttendanceGlobal(AttendanceDataBean attendanceDataBean,String personID);
	public String insertschool(LoginAccess loginaccess);
	public String saveAttendents(TeacherDataBean teacherDataBean);
	public String saveNotes(TeacherDataBean teacherDataBean);
	public String updateNotes(TeacherDataBean teacherDataBean);
	public String deleteNotes(TeacherDataBean teacherDataBean);
	public String saveActivity(StudentDataBean studentDataBean);
	public String updateActivity(StudentDataBean studentDataBean);
	public String saveAddActivity(StudentDataBean studentDataBean);
	public String deleteActivity(StudentDataBean studentDataBean);	
	public String updatefees(StudentDataBean studentDataBean);
	public String deletefeesDetails(StudentDataBean studentDataBean);
	public String payfees(StudentDataBean studentDataBean);	
	public String newschoolapproval(LoginAccess login);
	public String newschoolreject(LoginAccess login);
	public String schoolupdate(LoginAccess loginaccess);
	/* Return type List method */
	public List<String> getmenus();
	public List<String> classeslist(String personID);
	public List<String> getStateList(String personID);
	public List<String> getClassList(String personID);
	public List<String> getStateLists(String personID);
	public List<String> getSubjectList(String personID);
	public List<String> studentidlist(String personID);
	public List<String> getClassSection(String personID);
	public List<String> getClassListAtt(String personID);	
	public List<String> getClassNameList(String personID);
	public List<String> getcountryList(String valuechange);
	public List<String> classStudent(String personID, String string);
	public List<String> classNamesList(String personID, String status);
	public List<String> getStudentIDList1(String name, String personID);
	public List<String> getStudentRollNumber(String personID, String name);
	public List<String> getExamTitleName(String personID, String classname);
	public List<String> getstudentRollNumber(String personID, String classname);		
	public List<String> getSubjectListTeacher(String personID, String classname);
	public List<String> getClassList(String personID, StudentDataBean studentdatabean);
	public List<String> getIdList(StudentPerformanceDataBean studentPerformanceDataBean);
	public List<String> parentAttlist(String personID, AttendanceDataBean attendanceDataBean);
	public List<String> getBorrowedBook(String personID, String categoryname, String libStudID);
	public List<String> getStudentIDList(ReportCardDataBean reportCardDataBean, String personID);
	public List<String> getSubjectNameList(ReportCardDataBean reportCardDataBean, String personID);
	public List<String> ClassListAttView(String personID, AttendanceDataBean attendanceDataBean);
	public List<String> getexamViewList(String personID, TimeTableDataBean timeTableDataBean);
	public List<String> getstudentList(String personID, TimeTableDataBean timeTableDataBean);
	public List<String> getexamList(String personID, TimeTableDataBean timeTableDataBean);
	public List<String> getTeaClass(String rollnumber, StudentDataBean studentDataBean);
	public List<String> classSubjectList(HomeworkDatabean homeworkDatabean, String personD);
	public List<String> ClassListbooksale(String personID,BookSaleDataBean bookSaleDataBean);
	public List<String> getClassList1(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public List<String> getPerClassList1(String s,StudentPerformanceDataBean studentPerformanceDataBean);
	public List<String> subjectChange(String personID, ClassTimeTableDataBean classTimeTableDataBean);	
	public List<String> subjectCodeChange(String personID,ClassTimeTableDataBean classTimeTableDataBean);
	public List<String> getActivitieslist(StudentDataBean studentDataBean);
	public List<UserProduct> LoadMenu(LoginAccess loginaccess);
	public List<SupProduct> loadSubMenu(int product_ID, String string);
	public List<TeacherDataBean> getImagePath(String personID, String teaID);
	public List<StudentDataBean> getImagePath1(String personID, String stuRollNo);
	public List<StudentDataBean> getStudentInfo(String personID, StudentDataBean studentDataBean);
	public List<StudentDetail> getStudentView(StudentDataBean studentDataBean, String personID);
	public List<StudentDetail> getStudentDetails(StudentDataBean studentDataBean,String personID);
	public List<StudentDataBean> getAllStudentInfo(String personID);
	public List<com.stumosys.domain.TeacherDataBean> getAllTeacherInfo(String personID, TeacherDataBean teacherDataBean);
	public List<com.stumosys.domain.TeacherDataBean> getTeacherInfo(String personID, String teaID);
	public List<NoticeBoardDataBean> getNoticeBoardView(String personID);
	public List<Noticeboard> getNoticeBoardViewBYSubject(String personID, NoticeBoardDataBean noticeBoardDataBean,String role_user);
	public List<ParentsDataBean> getParentDetilsList(String personID, ParentsDataBean parentsDataBean);
	public List<ParentsDataBean> getParentInfo(String personID, ParentsDataBean parentsDataBean);
	public List<ReportCardDataBean> getStudent(String personID, ReportCardDataBean reportCardDataBean);
	public List<StudentPerformanceDataBean> getStudentPerInfo(String personID,StudentPerformanceDataBean studentPerformanceDataBean);
	public List<StudentPerformance> getPerformView(StudentPerformanceDataBean studentPerformanceDataBean);
	public List<StudentPerformance> getPerformDetails(StudentPerformanceDataBean studentPerformanceDataBean);
	public List<ReportCardDataBean> getRepoartCard(String personID, ReportCardDataBean reportCardDataBean);
	public List<LibraryDataBean> getBookListView(String personID, String name);
	public List<LibraryDataBean> getBookDetailsView(String personID, LibraryDataBean libraryDataBean);
	public List<LibraryDataBean> getBoorowerBookView(String personID, String name);
	public List<BookSaleDataBean> getBookInfo(String personID, BookSaleDataBean bookSaleDataBean);
	public List<BookSaleDataBean> getBookViewInfo(String personID, BookSaleDataBean bookSaleDataBean);
	public List<BookSalesRecord> getBookDetailInfo(String personID, BookSaleDataBean bookSaleDataBean);
	public List<BookSaleDataBean> getBookInfo1(String personID, BookSaleDataBean bookSaleDataBean);
	public List<ExamTable> getTimeTableList(String personID);
	public List<TimeTable> getExamTableList(String personID, int examID);
	public List<School> getAdminDetails(String personID, LoginAccess loginaccess);
	public List<ParentsDataBean> getImagePath2(String personID, String parParentID);
	public List<NoticeBoardDataBean> getAllUserList(String personID, NoticeBoardDataBean noticeBoardDataBean);
	public List<ClassTimeTableDataBean> getclassTimeTable(String personID);
	public List<StaffDataBean> getImagePath3(String personID, String staStaffID);
	public List<StaffDataBean> staffinfomation(String personID, StaffDataBean staffDataBean);
	public List<StaffDataBean> tagstaffview(String personID, StaffDataBean staffDataBean);
	public List<LibrarianDataBean> getImagePath5(String personID, String libID);
	public List<LibrarianDataBean> getAllLibrarianInfo(String personID);
	public List<HomeworkDatabean> getHomework(String personID);
	public List<LibraryDataBean> getBookListView1(String personID, String categoryname);	
	public List<StaffDataBean> getImagePathstaff3(String personID,String staStaffID);
	public List<PaymentDatabean> feesinfomation(String personID, PaymentDatabean paymentDatabean);
	public List<BookSaleDataBean> getBookView(String personID,BookSaleDataBean bookSaleDataBean);
	public List<LoginAccess> getSchoolsList(LoginAccess loginaccess);
	public List<School> schooledit(LoginAccess login);
	public List<ClassTimeTableDataBean> getstudentclassTimeTable(String personID, StudentDataBean studentDataBean);
	public List<LibraryDataBean> getBoorowerBookView1(String personID);
	public List<LibraryDataBean> getreturnBookView1(String personID);	
	public List<LibraryDataBean> getborrowerDetails(String personID, LibraryDataBean libraryDataBean);
	public List<Library> authernamelist(String authername, String personID);
	public List<Library> booknamelist(String personID);
	public List<LibraryDataBean> stuinfo(String personID, String sturollno);
	public List<LibrarianDataBean> classlistview(String personID,LibrarianDataBean librarianDataBean);
	public List<LibrarianDataBean> subjectlistview(String personID,LibrarianDataBean librarianDataBean);	
	public List<TimeTableDataBean> getexamMarksList(String personID,TimeTableDataBean timeTableDataBean);	
	public List<AttendanceDataBean> attendanceReport(String personID,AttendanceDataBean attendanceDataBean);	
	public List<ReportCardDataBean> getmarks(String personID,ReportCardDataBean reportCardDataBean);	
	public List<StudentPerformanceDataBean> getStudentperformance(String personID,StudentPerformanceDataBean studentPerformanceDataBean);
	public List<LoginAccess> searchvalues(String schoolID);
	public List<TeacherDataBean> getAttendentsDetail(TeacherDataBean teacherDataBean);	
	public List<TeacherDataBean> getNotesDetail(TeacherDataBean teacherDataBean);
	public List<StudentDataBean> getActivity(StudentDataBean studentDataBean);
	public List<AttendanceDataBean> attendanceSearch(String personID,AttendanceDataBean attendanceDataBean);
	public List<StudentDataBean> getstudentbehaviourList(StudentDataBean studentDataBean);
	public List<StudentDataBean> getFeesList(StudentDataBean studentDataBean);
	public List<ReportCardDataBean> getglobalsearchMarkList(String schoolID,String personID, ReportCardDataBean reportCardDataBean);
	public List<ExamTable> getglobalSearchTimeTableList(String schoolID,String personID, String className, String month);
	public String getexammarkgradeGlobal(ReportCardDataBean reportCardDataBean);
	public String addReportCardGlobal(String personID, ReportCardDataBean reportCardDataBean);
	public List<LoginAccess> getUserDetails(LoginAccess loginaccess);
	public String insertformdetails(LoginAccess loginaccess);
	public List<StudentDataBean> getStudentCommunitryDetail(String communitySearchType,StudentDataBean studentDataBean);
	public List<String> getTeachername(String schoolID);
	public List<String> getStudentname(String schoolID);
	public void getStudentdate(String personID, StaffDataBean staffDataBean);
	public String emisnoDetails(StaffDataBean staffDataBean);
	public String saveTC(StaffDataBean staffDataBean);
	public String changePassword(LoginAccess loginaccess);
	public List<String> getTeaClasslist(String personID);
	public void takeattendanceNew(String personID, AttendanceDataBean attendanceDataBean);
	public void attendanceStatusNew(String personID, AttendanceDataBean attendanceDataBean); 
	public String insertTermfees(StudentDataBean studentDataBean);
	public String insertAttandance(String personID, String schoolID, AttendanceDataBean attendanceDataBean);
	public String examDelete(TimeTableDataBean timeTable);
	public String gradeDelete(TimeTableDataBean timeTable); 
	
	public String saveReport(ReportDataBean reportDataBean);
	public List<ReportDataBean> getReportmenulist(ReportDataBean reportDataBean);
	public List<ReportDataBean> getFilterlist(ReportDataBean reportDataBean);
	public void classNamebasedData(ReportDataBean reportDataBean);
	public List<AttendanceDataBean> getAttendanceReport(ReportDataBean reportDataBean);
	public void secNamebasedData(ReportDataBean reportDataBean);
	public String deleteMenu(ReportDataBean reportDataBean);
	public List<StudentPerformanceDataBean> getBehaviourReport(ReportDataBean reportDataBean);
	public String updateMenuEdit(ReportDataBean reportDataBean);
	public List<String> getExamListforMark(ReportDataBean reportDataBean);
	public List<ReportCardDataBean> getReportCardReport(ReportDataBean reportDataBean); 

	public List<String> teacherNameList(ReportDataBean reportDataBean);
	public List<ReportDataBean> getTeacherAttendanceReport(ReportDataBean reportDataBean);
	public List<ReportDataBean> getTeacherTimetableReport(ReportDataBean reportDataBean);
	public List<String> subjectNameList(ReportDataBean reportDataBean); 
	public String getClassEdit(StudentDataBean studentDataBean,String personID);
}
