package com.stumosys.dao;

import java.util.List;

import com.stumosys.domain.AttendanceDataBean;
import com.stumosys.domain.BookSaleDataBean;
import com.stumosys.domain.ClassTimeTableDataBean;
import com.stumosys.domain.HomeworkDatabean;
import com.stumosys.domain.LibraryDataBean;
import com.stumosys.domain.LoginAccess;
import com.stumosys.domain.NoticeBoardDataBean;
import com.stumosys.domain.PaymentDatabean;
import com.stumosys.domain.ReportCardDataBean;
import com.stumosys.domain.StudentDataBean;
import com.stumosys.domain.StudentPerformanceDataBean;
import com.stumosys.domain.TimeTableDataBean;
import com.stumosys.shared.ExamTable;
import com.stumosys.shared.Noticeboard;
import com.stumosys.shared.Person;
import com.stumosys.shared.StudentPerformance;

public interface AdministrationDao {
	public String getRoll(String personID);
	public String getPerClass(PaymentDatabean paymentDatabean);
	public String getexammarkgrade(ReportCardDataBean reportCardDataBean);	
	public String feespay(String personID, PaymentDatabean paymentDatabean);
	public String insertfees(String personID, PaymentDatabean paymentDatabean);
	public String deleteBook(String personID, LibraryDataBean libraryDataBean);
	public String getStaffRollNumber(String personID, LoginAccess loginaccess);
	public String paymentview(String personID, PaymentDatabean paymentDatabean);
	public String toReturnBook(String personID, LibraryDataBean libraryDataBean);
	public String updatePayment(String personID, PaymentDatabean paymentDatabean);
	public String deletePayment(String personID, PaymentDatabean paymentDatabean);
	public String classChange(HomeworkDatabean homeworkDatabean, String personID);
	public String examCheck(TimeTableDataBean timeTableDataBean, String personID);
	public String updateLibrary(String personID, LibraryDataBean libraryDataBean);
	public String insertLibrary(String personID, LibraryDataBean libraryDataBean);
	public String checkHomeWork(HomeworkDatabean homeworkDatabean, String personID);
	public String examRecords(TimeTableDataBean timeTableDataBean, String personID);
	public String getmailsID(StudentPerformanceDataBean studentPerformanceDataBean);
	public String updateHomeWork(HomeworkDatabean homeworkDatabean, String personID);
	public String deleteHomeWork(HomeworkDatabean homeworkDatabean, String personID);
	public String homeWorkInsert(HomeworkDatabean homeworkDatabean, String personID);
	public String getPerClassList1(String personID, PaymentDatabean paymentDatabean);
	public String classPeriod(AttendanceDataBean attendanceDataBean, String personID);
	public String subjectValues(TimeTableDataBean timeTableDataBean, String personID);
	public String timeTableView(TimeTableDataBean timeTableDataBean, String personID);
	public String getexamupdate(String personID, TimeTableDataBean timeTableDataBean);
	public String studentList(String personID, AttendanceDataBean attendanceDataBean);
	public String approveRejectFees(String personID, PaymentDatabean paymentDatabean);
	public String insertBookBorrowed(String personID, LibraryDataBean libraryDataBean);
	public String classStudent(AttendanceDataBean attendanceDataBean, String personID);
	public String leaveRequest(AttendanceDataBean attendanceDataBean, String personID);
	public String getexamEditList(String personID, TimeTableDataBean timeTableDataBean);
	public String addReportCard(String personID, ReportCardDataBean reportCardDataBean);
	public String timeTableICheck(String personID, TimeTableDataBean timeTableDataBean);
	public String classStudentFeesView(String personID, PaymentDatabean paymentDatabean);
	public String deleteNotice(String personID, NoticeBoardDataBean noticeBoardDataBean);
	public String editReportCard(String personID, ReportCardDataBean reportCardDataBean);
	public String attendanceView(String personID, AttendanceDataBean attendanceDataBean);
	public String studentAttView(String personID, AttendanceDataBean attendanceDataBean);
	public String updateNotice(String personID, NoticeBoardDataBean noticeBoardDataBean);
	public String performanceCheck(StudentPerformanceDataBean studentPerformanceDataBean);
	public String getexammarksupdate(String personID,TimeTableDataBean timeTableDataBean);
	public String changeSubjectCode(String personID, TimeTableDataBean timeTableDataBean);
	public String attendanceChart(String personID, AttendanceDataBean attendanceDataBean);
	public String updateAttendance(AttendanceDataBean attendanceDataBean, String personID);
	public String attendanceStatus(String personID, AttendanceDataBean attendanceDataBean);
	public String parentstuAttView(String personID, AttendanceDataBean attendanceDataBean);
	public String getexamRecordsList(String personID, TimeTableDataBean timeTableDataBean);
	public String leaveRequsetView(AttendanceDataBean attendanceDataBean, String personID);
	public String getReportBarChart(String personID, ReportCardDataBean reportCardDataBean);
	public String leaveRequsetReject(AttendanceDataBean attendanceDataBean, String personID);
	public String insertNoticeBoard(String personID, NoticeBoardDataBean noticeBoardDataBean);
	public String classChange(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String leaveRequsetApproval(AttendanceDataBean attendanceDataBean, String personID);
	public String attendancePercentage(String personID, AttendanceDataBean attendanceDataBean);
	public String updateAttendanceGlobal(AttendanceDataBean attendanceDataBean,String personID);
	public String attendanceChartStudent(String personID, AttendanceDataBean attendanceDataBean);
	public String classTimeTable(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String checkExtraPeriod(String personID,ClassTimeTableDataBean classTimeTableDataBean);
	public String checkExtraClass(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String insertExtraClass(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public List<String> getSubjectNameList(ReportCardDataBean reportCardDataBean, String personID);
	public String insertExtraPeriod(String personID,ClassTimeTableDataBean classTimeTableDataBean);
	public String teacherTimeTable(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public String saveClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String classTimeTableView(ClassTimeTableDataBean classTimeTableDataBean, String personID);	
	public String attendanceChartStudentYear(String personID, AttendanceDataBean attendanceDataBean);
	public String getPerClass(StudentPerformanceDataBean studentPerformanceDataBean, String personID);
	public String classTimeTableDelete(ClassTimeTableDataBean classTimeTableDataBean, String personID);	
	public List<ReportCardDataBean> getStudent(String personID, ReportCardDataBean reportCardDataBean);
	public String updateClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String deleteClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String timeTableInsert(int examId, TimeTableDataBean timeTableDataBean, int i, int schoolId);
	public String getPerformEdit(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public String getperformDelete(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public String checkupdateClassTimeTable(ClassTimeTableDataBean classTimeTableDataBean, String personID);
	public String insertStudentPerform(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public List<Noticeboard> getNoticeBoardViewBYSubject(String personID, NoticeBoardDataBean noticeBoardDataBean,String role_user);

	public List<String> classeslist(String personID);
	public List<Person> getperson(String personID);
	public List<String> getClassList(String personID);
	public List<String> getClassListAtt(String personID);
	public List<String> getClassNameList(String personID);
	public List<NoticeBoardDataBean> getNoticeBoardView(String personID);
	public List<String> getIdList(StudentPerformanceDataBean studentPerformanceDataBean);
	public List<String> getStudentIDList(ReportCardDataBean reportCardDataBean, String personID);
	public List<String> getClassList1(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public List<StudentPerformance> getPerformView(StudentPerformanceDataBean studentPerformanceDataBean);
	public List<StudentPerformance> getPerformDetails(StudentPerformanceDataBean studentPerformanceDataBean);
	public List<String> getPerClassList1(String personID, StudentPerformanceDataBean studentPerformanceDataBean);
	public List<ReportCardDataBean> getRepoartCard(String personID, ReportCardDataBean reportCardDataBean);
	public List<ExamTable> examTableInsert(int schoolId, TimeTableDataBean timeTableDataBean, List<TimeTableDataBean> timesBean);
	public List<StudentPerformanceDataBean> getStudentPerInfo(String personID,StudentPerformanceDataBean studentPerformanceDataBean);
	public List<LibraryDataBean> getBookListView(String personID, String name);
	public List<String> getexamList(String personID, TimeTableDataBean timeTableDataBean);
	public List<LibraryDataBean> getBookDetailsView(String personID, LibraryDataBean libraryDataBean);
	public List<String> ClassListAttView(String personID, AttendanceDataBean attendanceDataBean);
	public List<String> parentAttlist(String personID, AttendanceDataBean attendanceDataBean);
	public List<String> getBorrowedBook(String personID, String categoryname, String libStudID);
	public List<LibraryDataBean> getBoorowerBookView(String personID, String name);
	public List<String> getExamTitleName(String personID, String className);
	public List<String> getStudentIDList1(String name, String personID);
	public List<String> getexamViewList(String personID, TimeTableDataBean timeTableDataBean);
	public List<String> getstudentList(String personID, TimeTableDataBean timeTableDataBean);
	public List<String> subjectChange(String personID, ClassTimeTableDataBean classTimeTableDataBean);
	public List<ClassTimeTableDataBean> getclassTimeTable(String personID);
	public List<String> classSubjectList(HomeworkDatabean homeworkDatabean, String personID);
	public List<String> classNamesList(String personID, String status);
	public List<HomeworkDatabean> getHomework(String personID);
	public List<String> ClassListbooksale(String personID,BookSaleDataBean bookSaleDataBean);
	public List<String> getstudentRollNumber(String personID, String classname);
	public List<LibraryDataBean> getBookListView1(String personID, String categoryname);	
	public List<String> getSubjectListTeacher(String personID, String classname);
	public List<String> getRollNumber1(String personID);
	public List<StudentDataBean> getStudentDetails(String stuRollNo, StudentDataBean studentDataBean);	
	public List<PaymentDatabean> feesinfomation(String personID, PaymentDatabean paymentDatabean);
	public List<String> classStudent(String personID, String string);
	public List<LibraryDataBean> getBoorowerBookView1(String personID);
	public List<LibraryDataBean> getreturnBookView1(String personID);	
	public List<LibraryDataBean> getborrowerDetails(String personID, LibraryDataBean libraryDataBean);	
	public List<TimeTableDataBean> getexamMarksList(String personID,TimeTableDataBean timeTableDataBean);	
	public List<AttendanceDataBean> attendanceReport(String personID,AttendanceDataBean attendanceDataBean);	
	public List<ReportCardDataBean> getmarks(String personID,ReportCardDataBean reportCardDataBean);	
	public List<StudentPerformanceDataBean> getStudentperformance(String personID,StudentPerformanceDataBean studentPerformanceDataBean);
	public List<String> subjectCodeChange(String personID,ClassTimeTableDataBean classTimeTableDataBean);	
	public List<String> getcountryList(String valuechange);
	public List<AttendanceDataBean> attendanceSearch(String personID,AttendanceDataBean attendanceDataBean);
	public List<ReportCardDataBean> getglobalsearchMarkList(String schoolID,String personID, ReportCardDataBean reportCardDataBean);
	public String getexammarkgradeGlobal(ReportCardDataBean reportCardDataBean);
	public String addReportCardGlobal(String personID, ReportCardDataBean reportCardDataBean);
	public void attendanceStatusNew(String personID, AttendanceDataBean attendanceDataBean);
	public String examDelete(TimeTableDataBean timeTable);
	public String gradeDelete(TimeTableDataBean timeTable); 
}
